package by.itacademy.matveenko.jd2.controller;

public enum CommandName {
	GO_TO_BASE_PAGE,
	GO_TO_REGISTRATION_PAGE, DO_REGISTRATION,
	GO_TO_NEWS_LIST, GO_TO_VIEW_NEWS,
	DO_SIGN_IN, DO_SIGN_OUT,	
	GO_TO_ADD_NEWS_PAGE, DO_ADD_NEWS,
	GO_TO_EDIT_NEWS_PAGE, DO_EDIT_NEWS,
	GO_TO_DELETE_NEWS_PAGE, DO_DELETE_NEWS
}